{
 "title": "operations timing",
 "time": { "from": "2022-03-31T14:37:47.547Z", "to": "2022-03-31T15:39:50.303Z" },
 "templating": {
  "list": [
   { "name": "operation", "query": "PROPFIND,MKCOL,PUT,MOVE,DELETE" }
  ]
 },
 "panels": [
  {
   "title": "active virtual users (VUS)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "iteration duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "iteration duration p(95)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iteration_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$operation duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "p(95) $__interval",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=~", "value": "/^$operation$/" }
     ]
    }
   ]
  },
  {
   "title": "$operation requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "successfull / 1s (moving avg 5s)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=~", "value": "/^$operation$/" },
      { "condition": "AND", "key": "expected_response", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "failed / 1s (moving avg 5s)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=~", "value": "/^$operation$/" },
      { "condition": "AND", "key": "expected_response", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "precondition_failed", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "precondition failed / 1s (moving avg 5s)",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=~", "value": "/^$operation$/" },
      { "condition": "AND", "key": "expected_response", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "precondition_failed", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "$operation requests per 60 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "sucessfull / 60s (moving avg)",
     "groupBy": [
      { "params": [ "2s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "*30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=~", "value": "/^$operation$/" },
      { "condition": "AND", "key": "expected_response", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "failed / 60s (moving avg)",
     "groupBy": [
      { "params": [ "2s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "*30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=~", "value": "/^$operation$/" },
      { "condition": "AND", "key": "expected_response", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "precondition_failed", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "precondition failed / 60s (moving avg)",
     "groupBy": [
      { "params": [ "2s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "*30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=~", "value": "/^$operation$/" },
      { "condition": "AND", "key": "expected_response", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "precondition_failed", "operator": "=", "value": "true" }
     ]
    }
   ]
  }
 ]
}